Update runners OS and dependencies  (#391)
* Switch runners to use nix

* Fix compiler not found in cmake

* Add compiler flag for older dep

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -1,14 +1,11 @@
 name: CQ CI - CMake Configure, Build, Test, Cache
-
 on:
   push:
     branches: dev
   pull_request:
-
 concurrency: 
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
-
 jobs:
    cmake-build:
     name: ${{ matrix.config.name }}
@@ -20,15 +17,21 @@ jobs:
         config:
           - {
             name: "GCC",
-            os: [self-hosted, gcc],
+            os: [self-hosted, nix],
             enable_mpi: OFF,
+            c_compiler: gcc,
+            cxx_compiler: g++,
+            fortran_compiler: gfortran,
             para_build_jobs: 7,
             para_test_jobs: 7
           }
           - {
             name: "GCC-MPI",
-            os: [self-hosted, gcc, mpi],
+            os: [self-hosted, nix],
             enable_mpi: ON,
+            c_compiler: mpicc,
+            cxx_compiler: mpicxx,
+            fortran_compiler: mpifort,
             para_build_jobs: 7,
             para_test_jobs: 4
           }           
@@ -47,42 +50,42 @@ jobs:
         uses: actions/cache@v3
         with:
           path: ~/.ccache
-          key: ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-${{ hashFiles('**/CMakeLists.txt') }}  # Unique key based on CMakeLists.txt and mpi enabled changes
+          key: ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-${{ hashFiles('**/CMakeLists.txt') }}
           restore-keys: |
             ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-
 
       - name: Install and configure ccache
         shell: bash
         run: |
-          if ! command -v ccache &> /dev/null; then
-            echo "ccache not found, please install it on runner."
-            exit 1
-          fi
-          ccache --zero-stats
-          ccache --show-config
+          nix develop /home/runners/nix-env --command bash -c '
+            if ! command -v ccache &> /dev/null; then
+              echo "ccache not found in nix flake shell."
+              exit 1
+            fi
+            ccache --zero-stats
+            ccache --show-config
+          '
 
       # Configure
       - name: Configure
         shell: bash
         working-directory: build
         run: |
-          source /usr/share/Modules/init/bash
-          source /etc/profile.d/modules.sh
-          export MODULEPATH=/home/modulefiles/compilers:/home/modulefiles/compiler_dep/gcc/10.2.0:/home/modulefiles:$MODULEPATH
-          module load gcc hdf5 libint
-          export PATH=/usr/lib64/openmpi/bin:$PATH
-          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/software/gcc/10/2/0/install/lib64:$LD_LIBRARY_PATH
-
-          cmake .. \
-            -DCQ_ENABLE_MPI=${{ matrix.config.enable_mpi }} \
-            -DCMAKE_BUILD_TYPE=Release \
-            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
-            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-            -DCMAKE_COLOR_DIAGNOSTICS=On \
-            -DBLAS_LIBRARIES=/usr/lib64/libopenblas.so \
-            -DLAPACK_LIBRARIES=/usr/lib64/libopenblas.so \
-            -G Ninja \
-            -S .. -B .
+          nix develop /home/runners/nix-env --command bash -c '
+            export OMPI_ALLOW_RUN_AS_ROOT=1
+            export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
+            cmake .. \
+              -DCQ_ENABLE_MPI=${{ matrix.config.enable_mpi }} \
+              -DCMAKE_BUILD_TYPE=Release \
+              -DCMAKE_C_COMPILER=${{ matrix.config.c_compiler }} \
+              -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx_compiler }} \
+              -DCMAKE_Fortran_COMPILER=${{ matrix.config.fortran_compiler }} \
+              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
+              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
+              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+              -DCMAKE_COLOR_DIAGNOSTICS=On \
+              -S .. -B .
+          '
 
       # Build
       - name: Build
@@ -90,11 +93,14 @@ jobs:
         working-directory: build
         run: |
           echo "Building with ${{ matrix.config.para_build_jobs }} threads"
-          cmake --build . --config Release --parallel ${{ matrix.config.para_build_jobs }}
+          nix develop /home/runners/nix-env --command bash -c '
+            cmake --build . --config Release --parallel ${{ matrix.config.para_build_jobs }}
+          '
 
       # Show ccache stats
       - name: Show ccache stats
-        run: ccache --show-stats
+        run: |
+          nix develop /home/runners/nix-env --command ccache --show-stats
 
       # Test
       - name: Test
@@ -102,15 +108,9 @@ jobs:
         working-directory: build
         run: |
           echo "Testing with ${{ matrix.config.para_test_jobs }} threads"
-          source /usr/share/Modules/init/bash
-          source /etc/profile.d/modules.sh
-          export MODULEPATH=/home/modulefiles/compilers:/home/modulefiles/compiler_dep/gcc/10.2.0:/home/modulefiles:$MODULEPATH
-          module load gcc hdf5 libint
-          export PATH=/usr/lib64/openmpi/bin:$PATH
-          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/software/gcc/10/2/0/install/lib64:$LD_LIBRARY_PATH
-          export OMPI_ALLOW_RUN_AS_ROOT=1 # Allow running OpenMPI as root if necessary
-          export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 # Confirm running OpenMPI as root if necessary
-
-          ctest -E "GPLHR" --output-on-failure --parallel ${{ matrix.config.para_test_jobs }}
-          ctest -R "GPLHR" --output-on-failure
-
+          nix develop /home/runners/nix-env --command bash -c '
+            export OMPI_ALLOW_RUN_AS_ROOT=1
+            export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
+            ctest -E "GPLHR" --output-on-failure --parallel ${{ matrix.config.para_test_jobs }}
+            ctest -R "GPLHR" --output-on-failure
+          '
